export type ExperimentStage = 'step1_stationary' | 'step2_moving_in' | 'step3_stationary_inside' | 'step4_moving_out' | 'step5_optimization' | 'restored'

export type ExperimentMetrics = {
  current: number
  voltage: number
  coilTurns: number
  magnetSpeed: number
  ironCoreInserted: boolean
  fieldVisible: boolean
}

export type BuildingKind = 'house' | 'school' | 'hospital' | 'waterPump'

export type GridNode = {
  id: string
  kind: BuildingKind
  label: string
  x: number
  y: number
  demand: number
  critical: boolean
  supplied: boolean
}

export type GeneratorNode = {
  id: string
  x: number
  y: number
  output: number
  placed: boolean
}

export type BatteryNode = {
  id: string
  x: number
  y: number
  capacity: number
  charge: number
  placed: boolean
}

export type CableConnection = {
  fromId: string
  toId: string
  length: number
  loss: number
}

export type GridState = {
  generators: GeneratorNode[]
  batteries: BatteryNode[]
  buildings: GridNode[]
  cables: CableConnection[]
  production: number
  demand: number
  batteryCharge: number
  allCriticalPowered: boolean
}

export const FARADAY_FRAGMENT = {
  id: 'electromagnetic_induction',
  name: 'Electromagnetic Induction',
  description: 'Electricity can be generated by a changing magnetic field.',
  color: 0x55d6ff,
}

